name: Dotnet core build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Unit Tests
        run: dotnet test
      - name: Build NuGet Package
        run: dotnet pack --configuration Release -o NuGetPackages
      - name: Deploy NuGet Package
        run: dotnet nuget push DV8.Html/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
        
